--- #YAML:1.0
name:               Catalyst-Authentication-Credential-Flickr
version:            0.04
abstract:           Flickr authentication for Catalyst
author:
    - M. Blom (blom@cpan.org)
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    Catalyst::Plugin::Authentication:  0.1
    Class::Accessor::Fast:  0
    Flickr::API:          1
    LWP::UserAgent:       5.802
    Test::MockObject:     0
    Test::More:           0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.46
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
